version: '3.7'

services:
  api:
    image: wiki-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - api.env
    command: npm run start:prod
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "3001:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wiki
